project:
  type: manuscript

manuscript:
  article: index.qmd
  meca-bundle: "manuscript1-meca.zip"
  code-links:
  - text: Additional Notebook
    icon: filetype-html
    href: https://jriveraespejo.github.io/betaprop.walkthrough.github.io/
  - text: Github repository
    icon: filetype-html
    href: https://github.com/jriveraespejo/paper1_manuscript.git
  - text: User-defined functions
    icon: file-code-fill
    href: code/user-defined-functions.R

execute:
  freeze: auto

format:
  html:
    comments:
      hypothesis: true
    google-scholar: true
    licence: 'CC BY-SA'
    toc: true
    toc-title: 'Table of Contents'
    toc-location: left
    fontsize: 12pt
    number-sections: true
    code-fold: true
    code-summary: "code"
    code-overflow: scroll
    #code-annotations: hover
    #code-line-numbers: false
    tbl-cap-location: top
    fig-cap-location: top
    default image extension: png
  docx: default
  jats: default
  agu-pdf: 
    keep-tex: true


