project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links:
    - text: User-defined functions
      icon: file-code
      href: code/user-defined-functions.R
  meca-bundle: "manuscript1-meca.zip"

execute:
  freeze: auto

format:
  html:
    comments:
      hypothesis: true
    google-scholar: true
    licence: 'CC BY-SA'
    toc: true
    toc-title: 'Table of Contents'
    toc-location: left
    fontsize: 11pt
    number-sections: true
    code-fold: show
    code-summary: "code"
    code-overflow: scroll
    #code-annotations: hover
    #code-line-numbers: false
    tbl-cap-location: top
    fig-cap-location: top
    default image extension: png
  docx: default
  jats: default
  agu-pdf: 
    keep-tex: true


